### ISSUE TITLE
[1.7.10][NEIaddons .4][MagicBees .16] NPE

### ISSUE THREAD

**Issue by MrGraphic** [bdew-minecraft/neiaddons#14]
There is a fork of MB that works in 1.7.10: https://bitbucket.org/Arkandos/magic-bees .
Unfortunelly something somwhere is not right:
java.lang.NullPointerException: Updating screen events
    at net.bdew.neiaddons.Utils.mergeStacks(Utils.java:129)
    at net.bdew.neiaddons.forestry.BaseProduceRecipeHandler$CachedProduceRecipe.<init>(BaseProduceRecipeHandler.java:62)
    at net.bdew.neiaddons.forestry.BaseProduceRecipeHandler.loadUsageRecipes(BaseProduceRecipeHandler.java:150)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
    at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
    at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:320)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:508)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:496)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Not sure on whose side problem lies so I also sent this log to Arkandos author of that fork.

**Comment by bdew** [comment]
I can't reproduce the crash but i guess this will work around it, please try this version: http://jenkins.bdew.net/job/neiaddons-1.7.10/5/artifact/build/libs/neiaddons-mc1710-1.12.0.5.jar

If it doesn't - i need more information, what species it crashes on (if you can pinpoint), what other mods are installed.

**Comment by MrGraphic** [comment]
Works now as expected. What I tried when crash occurred was recipe for simple comb from frestry and recipe for one of bees from MagicBees. Thanks!

**Comment by bdew** [comment]
Note that it's just a workaround for the crash. The real issue is that something (i guess one of MB bees) is returning a null ItemStack in the Map from getProducts/getSpecialty. This will most probably cause issues elsewhere.

**Comment by MrGraphic** [comment]
Yeah, it is all now in Arkandos hands.

**Comment by Arkandos** [comment]
I'll see what I can do. I didnt do much updating of the bee part and I dont remember that specific point.

**Comment by Arkandos** [comment]
Fixed on my end. Silly Thermalexpansion splitting up into different mods.
