### ISSUE TITLE
Failed to setup Worktable crafting overlay

### ISSUE THREAD

**Issue by MyEternity** [bdew-minecraft/neiaddons#25]
[23:02:11 WARN]: Failed to setup Worktable crafting overlay
java.lang.ClassNotFoundException: forestry.factory.gui.SlotCraftMatrix
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_31]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_31]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_31]
        at net.bdew.neiaddons.Utils.getAndCheckClass(Utils.java:25) ~[Utils.class:?]
        at net.bdew.neiaddons.forestry.AddonForestry.init(AddonForestry.java:101) [AddonForestry.class:?]
        at net.bdew.neiaddons.NEIAddons.init(NEIAddons.java:89) [NEIAddons.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691) [Loader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:324) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:280) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException

**Comment by MyEternity** [comment]
forestry_1.7.10-3.5.0.485-unstable.jar
neiaddons-mc1710-1.12.4.16.jar

**Comment by MyEternity** [comment]
Error while loading game. (Client and Server)

**Comment by bdew** [comment]
Should be fixed in this build http://jenkins.bdew.net/job/neiaddons-1.7.10/17/artifact/build/libs/neiaddons-mc1710-1.12.5.17.jar
