### ISSUE TITLE
Error thrown in console.

### ISSUE THREAD

**Issue by mlimburg** [bdew-minecraft/neiaddons#3]
Howdy, I'm currently testing a new 1.5.2 build for FTB and an error came up in console. This build contains Forestry 2.2.6.0, NEI 1.5.2.21, NEI Plugins 1.0.9.1a and NEI Addons 1.6.1.r13 (plus more, of course).

2013-05-30 12:07:38 [WARNING] [NEIAddons] Addon Forestry failed client initialization: java.lang.NoSuchMethodError: forestry.api.genetics.IAlleleRegistry.getRegisteredAlleles()Ljava/util/LinkedHashMap;
2013-05-30 12:07:38 [INFO] [STDERR] java.lang.NoSuchMethodError: forestry.api.genetics.IAlleleRegistry.getRegisteredAlleles()Ljava/util/LinkedHashMap;
2013-05-30 12:07:38 [INFO] [STDERR]     at net.bdew.neiaddons.forestry.GeneticsUtils.getAllTypedSpecies(GeneticsUtils.java:98)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.bdew.neiaddons.forestry.GeneticsUtils.getAllBeeSpecies(GeneticsUtils.java:88)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.bdew.neiaddons.forestry.bees.BeeHelper.setup(BeeHelper.java:49)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.bdew.neiaddons.forestry.AddonForestry.loadClient(AddonForestry.java:75)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.bdew.neiaddons.NEIAddonsConfig.loadConfig(NEIAddonsConfig.java:22)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.nei.NEIClientConfig.loadConfig(NEIClientConfig.java:704)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:301)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:119)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.nei.NEICPH.handlePacket(NEICPH.java:27)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.core.packet.PacketCustom$ClientPacketHandler.handle(PacketCustom.java:102)
2013-05-30 12:07:38 [INFO] [STDERR]     at codechicken.core.packet.PacketCustom$CustomPacketHandler.onPacketData(PacketCustom.java:73)
2013-05-30 12:07:38 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
2013-05-30 12:07:38 [INFO] [STDERR]     at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
2013-05-30 12:07:38 [INFO] [STDERR]     at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:84)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.client.multiplayer.NetClientHandler.func_72501_a(NetClientHandler.java:1571)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:59)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.network.MemoryConnection.func_74428_b(MemoryConnection.java:89)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1899)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:835)
2013-05-30 12:07:38 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:760)
2013-05-30 12:07:38 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)

**Comment by bdew** [comment]
NEI Addons doesn't work with latest forestry due to API changes, i'll release an update soon

**Comment by mlimburg** [comment]
Awesome, will package it into a new pack as soon as you do. Thanks mate.
