### ISSUE TITLE
Errors with forestry_1.7.10-4.0.0.644-unstable

### ISSUE THREAD

**Issue by Xen1290** [bdew-minecraft/neiaddons#42]
Hi @bdew , I get this error in console:

[18:22:28] [Client thread/WARN] [NEIAddons]: Addon Forestry failed client initialization
java.lang.NoSuchMethodError: forestry.api.apiculture.IAlleleBeeSpecies.getProducts()Ljava/util/Map;
at net.bdew.neiaddons.forestry.GeneticsUtils.getProduceFromSpecies(GeneticsUtils.java:106) ~[GeneticsUtils.class:?]
at net.bdew.neiaddons.forestry.bees.BeeHelper.setup(BeeHelper.java:83) ~[BeeHelper.class:?]
at net.bdew.neiaddons.forestry.AddonForestry.loadClient(AddonForestry.java:127) ~[AddonForestry.class:?]
at net.bdew.neiaddons.NEIAddonsConfig.loadConfig(NEIAddonsConfig.java:21) [NEIAddonsConfig.class:?]
at codechicken.nei.NEIClientConfig.bootNEI(NEIClientConfig.java:278) [NEIClientConfig.class:?]
at codechicken.nei.NEIClientConfig.loadWorld(NEIClientConfig.java:208) [NEIClientConfig.class:?]
at codechicken.nei.NEICPH.handleSMPCheck(NEICPH.java:109) [NEICPH.class:?]
at codechicken.nei.NEICPH.handlePacket(NEICPH.java:23) [NEICPH.class:?]
at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:100) [PacketCustom$ClientInboundHandler.class:?]
at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:77) [PacketCustom$CustomInboundHandler.class:?]
at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:64) [PacketCustom$CustomInboundHandler.class:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:273) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:363) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

neiaddons-1.12.11.36-mc1.7.10
forestry_1.7.10-4.0.0.644-unstable

**Comment by bdew** [comment]
Forestry unstable 4.0 is currently unsupported due to incompatible changes.

I might make a separate build for forestry unstable (a-la gendustry-fu) in the future if Forestry 4.0 takes a long time to come out.

**Comment by Xen1290** [comment]
Ok, thanks!

**Comment by bdew** [comment]
http://jenkins.bdew.net/job/neiaddons-fu/
